stages:
  - package

copy_env_json_to_artifact:
  stage: package
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
  script:
    - test -f env.json || (echo "env.json not found" && exit 1)
    - mkdir -p artifacts
    - cp env.json artifacts/env.json
    - echo "Copied env.json to artifacts/env.json"
  artifacts:
    name: "env-json-$CI_COMMIT_SHORT_SHA"
    paths:
      - artifacts/env.json
    expire_in: 7 days
